### PR TITLE
FirstLoadingScreen; part2

### PR DESCRIPTION
**Pull request by ALiwoto**
## Purposes:
- [x] Moving all `ErrorSandBoxes` from `GUISharp` to `LTW.SandBoxes.ErrorSandBoxes`
- [ ] Check for current Game version from the server, and update the game if it's available.
- [x] Show `NoInternetConnectionSandBox` to the player if they don't have access to internet.
- [x] Show the main menu to player (with the options).
- [ ] Show `LoginProfileSandBox` to the players (if and only if they didn't login before).

### CODE REVIEW

**Comment by ALiwoto** [comment]
`ConnectionClosedSandBox`:
Screenshot from 2021-07-08 17-10-54
<hr/>

`NoInternetConnectionSandBox`:
Screenshot from 2021-07-08 17-53-48

<hr/>

`ProfileWrongSandBox`:
Screenshot from 2021-07-08 17-54-45
<hr/>

**Comment by ALiwoto** [comment]
Compile error

**Review by RokuroBenio — APPROVED** [review]

**Review by ArthuriaDX — APPROVED** [review]
approved

**Comment by ALiwoto** [comment]
> ## Purposes:
> 
>     * [x]  Moving all `ErrorSandBoxes` from `GUISharp` to `LTW.SandBoxes.ErrorSandBoxes`
> 
>     * [ ]  Check for current Game version from the server, and update the game if it's available.
> 
>     * [x]  Show `NoInternetConnectionSandBox` to the player if they don't have access to internet.
> 
>     * [x]  Show the main menu to player (with the options).
> 
>     * [ ]  Show `LoginProfileSandBox` to the players (if and only if they didn't login before).

(and update the game if it's available.) => this feature is not available at the moment
have to work on it later.

**Comment by ArthuriaDX** [comment]
I will merge it then

**Comment by RokuroBenio** [comment]
Also last one `Show LoginProfileSandBox to the players (if and only if they didn't login before).` is not for `FirstLoadingScreen` at all, it should be in main menu

**Pull request merged**
